### ISSUE TITLE
Colored grades

### ISSUE THREAD

**Issue by logicguy1** [logicguy1/FOSS-Lectio-improvements#10]
Would be kinda cool to add a grade grade*ient* where good grades are green, and bad are red yellow etc

**Comment by logicguy1** [comment]
This has been implemented in f892b42
![image](https://github.com/logicguy1/FOSS-Lectio-improvements/assets/56993729/3a4f7260-7ddf-4399-bade-69e09ec45998)
![image](https://github.com/logicguy1/FOSS-Lectio-improvements/assets/56993729/b5eae694-fd32-4ec2-a3e1-6d0974adcff9)

**Comment by Reikimann** [comment]
Commit f892b42 fixed this issue

**Comment by Reikimann** [comment]
![image](https://github.com/logicguy1/FOSS-Lectio-improvements/assets/78156411/0c9e4ae6-1e90-4234-8666-bf73a9c4bedf)
Grades not properly colored

**Comment by logicguy1** [comment]
I think its fine >:(
